### ISSUE TITLE
Need example with angular + es6 !

### ISSUE THREAD

**Issue by dmartinho** [princed/angular-gettext-loader#1]
Webpack noob here !
Ok i'm trying to use your loader without any result.

My project is an angular with es6 (babel loader) and i'm using angular gettext for translation.

I'm using the module config : 
`
        {  
          test: /\.po$/,
          loader: 'angular-gettext'
        },
` 
But it seems it doesn't work. Can you give me any example ?

**Comment by princed** [comment]
Did you require your translated `.po` file in your code? 
After that you need to change language to see translation an action, see https://angular-gettext.rocketeer.be/dev-guide/configure/.

**Comment by dmartinho** [comment]
Nope, so my problem is solved since i added the missing require. 

Thank you !

**Comment by princed** [comment]
My pleasure.
